sudo: required
language: node_js
node_js:
- '0.10'
addons:
  firefox: "42.0"
  apt:
    packages:
    - google-chrome-stable

before_script:
  - sudo apt-get update
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
