language: node_js
node_js:
- '0.10'
env:
    global:
        - secure: "GVP7McS2vu7t+Wl7oPQ7eVcclUM62kg/gZP+Z1e4AJPK5EfCzddPyt9Xv1pu0uc5xt8dqFJmniSJ+iOu6xGtpS4SSZipWKZVcptIDbIUSEizcUY3gz7HpUa+dyfYbGeRUreSmv4RnFRrSljbEmn9blV2EMl5R//XvCzbVYOhuFw="
        - secure: "A0iy6E6POTEImZ62WS0TgEs3Cy3+7XDAHD5PvEs6V1WmP+YYmMT2GmyjMVLZUyrAkNwJwBXhzUjJJJ9sx2q0OVTz8u9FVSLU9uaOxBXUPibt7EixDKPuVI4/QrkjYGHHDg3rjHGXeF20wREXCt611Gt/vHt+AoPrAocES5HI14w="
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

